### PR TITLE
Some fixes for v1.0

### LINKED ISSUE #54: gplothtml doesn't work
I get the following error with julia v0.6.1, GraphPlot  0.2.0  and Compose 0.5.4

    julia> gplothtml(graphfamous("karate"))
     WARNING: takebuf_string(b) is deprecated, use String(take!(b)) instead.
     Stacktrace:
      [1] depwarn(::String, ::Symbol) at ./deprecated.jl:70
      [2] takebuf_string(::Base.AbstractIOBuffer{Array{UInt8,1}}) at ./deprecated.jl:57
      [3] #gplothtml#39(::GraphPlot.#spring_layout, ::Array{Any,1}, ::Function, ::LightGraphs.SimpleGraphs.SimpleGraph{Int64}) at ~/.julia/v0.6/GraphPlot/src/plot.jl:248
      [4] gplothtml(::LightGraphs.SimpleGraphs.SimpleGraph{Int64}) at ~/.julia/v0.6/GraphPlot/src/plot.jl:242
      [5] eval(::Module, ::Any) at ./boot.jl:235
      [6] eval_user_input(::Any, ::Base.REPL.REPLBackend) at ./REPL.jl:66
      [7] macro expansion at ./REPL.jl:97 [inlined]
      [8] (::Base.REPL.##1#2{Base.REPL.REPLBackend})() at ./event.jl:73
     while loading no file, in expression starting on line 0
     ERROR: UndefVarError: OS_NAME not defined
     Stacktrace:
      [1] open_file(::String) at ~/.julia/v0.6/GraphPlot/src/plot.jl:229
      [2] #gplothtml#39(::GraphPlot.#spring_layout, ::Array{Any,1}, ::Function, ::LightGraphs.SimpleGraphs.SimpleGraph{Int64}) at ~/.julia/v0.6/GraphPlot/src/plot.jl:270
      [3] gplothtml(::LightGraphs.SimpleGraphs.SimpleGraph{Int64}) at ~/.julia/v0.6/GraphPlot/src/plot.jl:242
          
I can use Compose to draw an svg without problem.

     julia> Compose.draw(Compose.SVG("dessin.svg", 20cm, 20cm), gplot(graphfamous("karate")))
     false
     => svg created as expected

### PR DESCRIPTION
**Pull request by simonschoelly**
See #65 
I fixed some things to make this work on Julia 1.0 .  Unfortunately `Compose.jl` is not yet ready and produces a stack overflow when trying to print a `Compose.Context` to the console and there also seem to be some other problems when running the tests for `GraphPlot.jl`.

What doesn't work: 
```
using LightGraphs, GraphPlot
g = CompleteGraph(3)
gplot(g)
```
what works:
```
using LightGraphs, GraphPlot, Cairo
g = CompleteGraph(3)
draw(PDF("test.pdf", 16cm,16cm), gplot(g))
```
and 
```
using LightGraphs, GraphPlot
g = CompleteGraph(3)
gplothtml(g)
```
So this also seems to fix #54 

Unfortunately, I also had to add `Arpack.jl` to the requirements. And I took the liberty of bumping the version requirement to `0.7`.

### CODE REVIEW

**Comment by simonschoelly** [comment]
Strangely, Github somehow shows a commit for a different pr (from a different branch) in the commit tab for this pr.

**Comment by simonschoelly** [comment]
The problems with Compose are now fixed and we just have to wait for them to tag a new version. In the meantime, adding `Compose#master` should make this pr already work, for those who need it.

There was a strange problem on my computer. Apparently it is not enough to specify `VisualRegressionTests 0.2.2` in `tests/REQUIRE` but it also has to be specified in `REQUIRE`, even though it is only used for testing. We will have to check if this is also the case on travis or if this is just a problem with my computer.

File: REQUIRE [hunk 1]
```diff
@@ -1,4 +1,5 @@
-julia 0.6
+julia 0.7
+Arpack
```
Comment (jpfairbanks) [inline REQUIRE]: do we need this? Can we use the LightGraphs@1.1 LightGraphs.LinAlg.eigs?

File: src/layout.jl [hunk 2]
```diff
@@ -259,7 +261,7 @@ function _spectral(A::SparseMatrixCSC)
     D = sparse([1:length(data)], [1:length(data)], data)
     L = D - A
     ncv = max(7, int(sqrt(length(data))))
-    eigenvalues, eigenvectors = eigs(L, nev=3, ncv=ncv)
+    eigenvalues, eigenvectors = LightGraphs.LinAlg.eigs(L, nev=3, ncv=ncv)
```
Comment (jpfairbanks) [inline src/layout.jl]: you will need to specify the which=LR() for this eigs call.
and using ArnoldiMethods in order for this to work

Comment (simonschoelly) [reply src/layout.jl]: Ah I see, I though I thought `LightGraphs.LinAlg.eigs`  was just an identical replacement for the old `eigs` functions. Any reason why I should use `LightGraphs.LinAlg.eigs` instead of `partialschur` directly?
